#! /usr/bin/bash
#SBATCH --job-name=central
#SBATCH --partition=pe2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=20G
#SBATCH --time=10:00:00

source ~/anaconda3/bin/activate ~/anaconda3/envs/pytorch_env/
conda activate pytorch_env
python /gpfs/commons/groups/gursoy_lab/aelhussein/patient_pfl/20_sites/code/centralsite.py 
